### ISSUE TITLE
Thumbnails should disappear when only 1 image present

### ISSUE THREAD

**Issue by bacounts** [CodyHouse/cd-thumbnail-slideshow-changelog#1]
Is there a way to get a setting to make the thumbnails disappear when only one slideshow image is present?

**Comment by bacounts** [comment]
Any update on this issue? This is especially problematic when using the component with an eComm system like Shopify. When there is only one product picture, it seems odd to have the single thumbnail shown, given the image is large above it.

**Comment by claudia-romano** [comment]
Hi there, you could add the 'is-hidden' class to the `.thumbslide__nav-wrapper` when you have a single item. This will hide the thumbnail.

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you are still experiencing this issue. Cheers!
